info/modules/news/__init__.py
from flask import Blueprint

# 1. 创建蓝图
news_blu = Blueprint("news", __name__, url_prefix="/news")

# 4. 关联视图函数(避免循环导入)
from .views import *

info/modules/news/views.py
from flask import render_template, current_app, abort, session, g, request, jsonify

from info import db
from info.models import News, User, Comment
from info.modules.news import news_blu


# 新闻详情
from info.utils.common import user_login_data
from info.utils.response_code import RET, error_map


@news_blu.route('/<int:news_id>')  # 路由变量接收新闻id
@user_login_data  # 装饰器形式来封装用户信息的查询  news_detail = user_login_data(news_detail)
def news_detail(news_id):
    # 根据新闻id查询该新闻数据
    try:
        news = News.query.get(news_id)
    except BaseException as e:
        current_app.logger.error(e)
        abort(500)

    # 按照`点击量`查询`前10条`新闻数据
    news_list = []
    try:
        news_list = News.query.order_by(News.clicks.desc()).limit(10).all()
    except BaseException as e:
        current_app.logger.error(e)

    news_list = [news.to_dict() for news in news_list]

    # 点击量加1
    news.clicks += 1

    # 查询当前用户是否收藏了新闻
    user = g.user
    is_collected = False  # 记录是否收藏
    if user:  # 用户登录
        if news in user.collection_news:
            is_collected = True

    # 查询该新闻的所有评论  按照生成日期排序
    comments = []
    try:
        comments = news.comments.order_by(Comment.create_time.desc()).all()
    except BaseException as e:
        current_app.logger.error(e)

    # 正常情况下, 查询到某个数据后, 关系属性会将该数据的所有关联数据都查询出来(如果不需要关联数据,会很影响性能)
    # 可以给关系属性设置lazy参数="dynamic", 这样关系属性就不会自动查询关联数据, 而是使用具体查询查询条件时才会查询(all/count/first)
    # 查询哪些评论被当前用户点过赞
    comment_list = []
    for comment in comments:
        comment_dict =  comment.to_dict()
        is_like = False

        if user:  # 用户已登录
            # 该评论是否被"我"点赞
            # 设置了lazy的关系属性在和in联用时, 会自动进行all()查询
            if comment in user.like_comments:
                is_like = True

        # 定义键值对记录是否被当前用户点过赞
        comment_dict["is_like"] = is_like
        comment_list.append(comment_dict)

    # 查询作者是否被当前用户关注
    is_followed = False  # 记录是否已关注
    # 当前已登录, 并且新闻有作者
    if user and news.user:
        # 作者是否被当前用户关注
        if news.user in user.followed:
            is_followed = True

    # 将模型转为字典
    user = user.to_dict() if user else None

    # 将数据传入模板渲染
    return render_template("news/detail.html", news=news.to_dict(), news_list=news_list, user=user, is_collected=is_collected, comments=comment_list, is_followed=is_followed)


# 新闻收藏
@news_blu.route('/news_collect', methods=['POST'])
@user_login_data
def news_collect():
    # 判断用户是否登录
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg=error_map[RET.SESSIONERR])

    # 获取参数
    news_id = request.json.get("news_id")
    action = request.json.get("action")
    # 校验参数
    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])
    
    if action not in ["collect", "cancel_collect"]:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    try:  # 格式转换
        news_id = int(news_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])
    
    # 查询并校验是否存在该新闻    
    try:
        news = News.query.get(news_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg=error_map[RET.DBERR])
    
    if not news:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 根据action执行收藏/取消收藏  (使用关系属性来建立/解除关系)
    if action == "collect":  # 收藏
        user.collection_news.append(news)
    else:  # 取消收藏
        user.collection_news.remove(news)
        
    # json返回结果
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK])


# 新闻评论/子评论
@news_blu.route('/news_comment', methods=['POST'])
@user_login_data
def news_comment():
    # 判断用户是否登录
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg=error_map[RET.SESSIONERR])

    # 获取参数
    comment_content = request.json.get("comment")
    news_id = request.json.get("news_id")
    parent_id = request.json.get("parent_id")
    # 校验参数
    if not all([comment_content, news_id]):
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 校验新闻是否存在
    try:
        news_id = int(news_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    try:
        news = News.query.get(news_id)
    except BaseException as e:
        return jsonify(errno=RET.DBERR, errmsg=error_map[RET.DBERR])

    if not news:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 生成评论模型
    comment = Comment()
    comment.content = comment_content
    comment.user_id = user.id
    comment.news_id = news.id
    if parent_id:  # 子评论
        try:
            parent_id = int(parent_id)
            comment.parent_id = parent_id
        except BaseException as e:
            current_app.logger.error(e)

    try:
        db.session.add(comment)
        db.session.commit()  # 此处必须主动提交, 否则不会生成评论id, 无法回传给前端评论id

    except BaseException as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg=error_map[RET.DBERR])

    # 返回json  需要返回评论数据
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK], data=comment.to_dict())


# 评论点赞
@news_blu.route('/comment_like', methods=['POST'])
@user_login_data
def comment_like():
    # 判断用户是否登录
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg=error_map[RET.SESSIONERR])

    # 获取参数
    comment_id = request.json.get("comment_id")
    action = request.json.get("action")
    # 校验参数
    if not all([comment_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    if action not in ["add", "remove"]:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    try:  # 格式转换
        comment_id = int(comment_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 查询并校验是否存在该评论
    try:
        comment = Comment.query.get(comment_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg=error_map[RET.DBERR])

    if not comment:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 根据action执行点赞/取消点赞  (使用关系属性来建立/解除关系)
    if action == "add":  # 点赞
        user.like_comments.append(comment)
        comment.like_count += 1
    else:  # 取消点赞
        user.like_comments.remove(comment)
        comment.like_count -= 1

    # json返回结果
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK])


# 关注作者
@news_blu.route('/followed_user', methods=['POST'])
@user_login_data
def followed_user():
    # 判断用户是否登录
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg=error_map[RET.SESSIONERR])

    # 获取参数
    author_id = request.json.get("user_id")
    action = request.json.get("action")
    # 校验参数
    if not all([author_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    if action not in ["follow", "unfollow"]:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    try:  # 格式转换
        author_id = int(author_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 查询并校验是否存在该作者
    try:
        author = User.query.get(author_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg=error_map[RET.DBERR])

    if not author:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 根据action执行滚珠/取消关注  (使用关系属性来建立/解除关系)
    if action == "follow":  # 关注
        user.followed.append(author)
    else:  # 取消关注
        user.followed.remove(author)

    # json返回结果
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK])

info/modules/user/__init__.py
from flask import Blueprint

# 1. 创建蓝图
user_blu = Blueprint("user", __name__, url_prefix="/user")

# 4. 关联视图函数(避免循环导入)
from .views import *

info/modules/user/views.py
from flask import render_template, g, redirect, url_for, abort, request, jsonify, current_app

from info import db
from info.constants import USER_COLLECTION_MAX_NEWS, QINIU_DOMIN_PREFIX
from info.models import tb_user_collection, Category, News
from info.modules.user import user_blu
from info.utils.common import user_login_data, file_upload

# 个人中心
from info.utils.response_code import RET, error_map


@user_blu.route('/user_info')
@user_login_data
def user_info():
    user = g.user
    if not user:  # 用户未登录, 直接跳转到首页
        return redirect(url_for("home.index"))

    return render_template("news/user.html", user=user.to_dict())


# 基本资料
@user_blu.route('/base_info', methods=['GET', "POST"])
@user_login_data
def base_info():
    user = g.user
    if not user:
        return abort(403)  # 拒绝访问

    if request.method == 'GET':
        return render_template("news/user_base_info.html", user=user.to_dict())
    # POST处理
    signature = request.json.get("signature")
    nick_name = request.json.get("nick_name")
    gender = request.json.get("gender")

    # 校验参数
    if not all([signature, nick_name, gender]):
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])
    
    if gender not in ["MAN", "WOMAN"]:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 修改用户模型
    user.signature = signature
    user.nick_name = nick_name
    user.gender = gender

    # json返回  需要传入用户信息, 以便前端进行渲染
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK], data=user.to_dict())


# 显示/修改头像
@user_blu.route('/pic_info', methods=['GET', 'POST'])
@user_login_data
def pic_info():
    user = g.user
    if not user:
        return abort(403)  # 拒绝访问

    if request.method == 'GET':
        return render_template("news/user_pic_info.html", user=user.to_dict())
    # POST处理
    file = request.files.get("avatar")
    try:
        img_bytes = file.read()  # 读取上传文件的二进制格式数据  bytes
        # 一般上传的文件会放到一个单独的文件服务器中进行管理  只需要获取文件名
        try:
            file_name = file_upload(img_bytes)
        except BaseException as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.THIRDERR, errmsg=error_map[RET.THIRDERR])

        # 修改用户模型
        user.avatar_url = file_name

    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 需要回传用户信息, 以便前端来更新头像
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK], data=user.to_dict())
    

# 我的收藏列表
@user_blu.route('/collection')
@user_login_data
def collection():
    user = g.user
    if not user:
        return abort(403)  # 拒绝访问

    # 获取参数
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except BaseException as e:
        current_app.logger.error(e)
        return abort(403)

    # 查询当前用户收藏的所有新闻  按照收藏时间倒序
    try:
        pn = user.collection_news.order_by(tb_user_collection.c.create_time.desc()).paginate(p, USER_COLLECTION_MAX_NEWS)
    except BaseException as e:
        current_app.logger.error(e)

    data = {
        "news_list": [news.to_dict() for news in pn.items],
        "cur_page": p,
        "total_page": pn.pages
    }

    # 将新闻数据传入模板渲染
    return render_template("news/user_collection.html", data=data)


# 显示/修改密码
@user_blu.route('/pass_info', methods=['GET', 'POST'])
@user_login_data
def pass_info():
    user = g.user
    if not user:
        return abort(403)  # 拒绝访问

    if request.method == 'GET':  # 显示页面
        return current_app.send_static_file("news/html/user_pass_info.html")

    # POST处理
    # 获取参数
    old_password = request.json.get("old_password")
    new_password = request.json.get("new_password")
    # 校验参数
    if not all([old_password, new_password]):
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])
    # 校验密码
    if not user.check_password(old_password):  # 密码错误
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])
    # 修改密码(修改模型)
    user.password = new_password
    # json返回
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK])


# 新闻发布
@user_blu.route('/news_release', methods=['GET', 'POST'])
@user_login_data
def news_release():
    user = g.user
    if not user:
        return abort(403)  # 拒绝访问

    if request.method == 'GET':  # 显示页面
        # 查询所有的分类, 传入模板
        try:
            categories = Category.query.all()
        except BaseException as e:
            current_app.logger.error(e)
            return abort(403)  # 拒绝访问

        if len(categories):  # 删除最新
            categories.pop(0)

        return render_template("news/user_news_release.html", categories=categories)

    # POST处理
    title = request.form.get("title")
    category_id = request.form.get("category_id")
    digest = request.form.get("digest")
    content = request.form.get("content")
    if not all([title, category_id, digest, content]):
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    try:
        category_id = int(category_id)
        category = Category.query.get(category_id)
    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    if not category:
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])

    # 生成新闻数据
    news = News()
    news.title = title
    news.digest = digest
    news.content = content
    news.category_id = category_id
    news.source = "个人发布"  # 新闻来源
    news.user_id = user.id  # 新闻作者
    news.status = 1  # 状态 1表示待审核
    # 设置图片
    try:
        img_bytes = request.files.get("index_image").read()
        # 上传图片, 获取图片的访问链接
        try:
            file_name = file_upload(img_bytes)
            news.index_image_url = QINIU_DOMIN_PREFIX + file_name

        except BaseException as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.THIRDERR, errmsg=error_map[RET.THIRDERR])

    except BaseException as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg=error_map[RET.PARAMERR])


    db.session.add(news)
    
    return jsonify(errno=RET.OK, errmsg=error_map[RET.OK])


# 我的发布列表
@user_blu.route('/news_list')
@user_login_data
def news_list():
    user = g.user
    if not user:
        return abort(403)  # 拒绝访问

    # 获取参数
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except BaseException as e:
        current_app.logger.error(e)
        return abort(403)

    # 查询当前用户发布的所有新闻  按照发布时间倒序
    try:
        pn = user.news_list.order_by(News.create_time.desc()).paginate(p, USER_COLLECTION_MAX_NEWS)
    except BaseException as e:
        current_app.logger.error(e)

    data = {
        "news_list": [news.to_review_dict() for news in pn.items],
        "cur_page": p,
        "total_page": pn.pages
    }

    # 将新闻数据传入模板渲染
    return render_template("news/user_news_list.html", data=data)


# 我的关注列表
@user_blu.route('/user_follow')
@user_login_data
def user_follow():
    user = g.user
    if not user:
        return abort(403)  # 拒绝访问

    # 获取参数
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except BaseException as e:
        current_app.logger.error(e)
        return abort(403)

    # 查询当前用户关注的所有作者
    try:
        pn = user.followed.paginate(p, USER_COLLECTION_MAX_NEWS)
    except BaseException as e:
        current_app.logger.error(e)

    data = {
        "author_list": [author.to_dict() for author in pn.items],
        "cur_page": p,
        "total_page": pn.pages
    }

    # 将新闻数据传入模板渲染
    return render_template("news/user_follow.html", data=data)

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {% block title_block %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    <script type="text/javascript" src="../../static/news/js/csrf.js"></script>
    {% block scirpt_block %}

    {% endblock %}
</head>
<body>
<div class="header_con">
    <div class="header">
        <a href="{{ url_for("home.index") }}" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
        {% block category_block %}

        {% endblock %}

        {% if user %}

            <div class="user_login fr">
                <img {% if user.avatar_url %}src="{{ user.avatar_url }}"
                     {% else %}src="../../static/news/images/person01.png"{% endif %} class="lgin_pic">
                <a href="{{ url_for("user.user_info") }}" id="nick_name">{{ user.nick_name }}</a>
                <a href="javascript:;" onclick="logout()">退出</a>
            </div>

        {% else %}

            <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>

        {% endif %}
    </div>
</div>

<div class="conter_con">
    {% block content_block %}

    {% endblock %}
    {% block rank_block %}
        <div class="rank_con fr">
            {% block author_block %}

            {% endblock %}
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">
                {% for news in news_list %}
                    <li><span class="{{ loop.index | index_convert }}">{{ loop.index }}</span><a
                            href="/news/{{ news.id }}">{{ news.title }}</a></li>
                {% endfor %}

            </ul>
        </div>
    {% endblock %}

</div>
{% block footer_block %}
<div class="footer">
    <div class="footer_links">
        <a href="">关于我们</a>
        <span>|</span>
        <a href="">联系我们</a>
        <span>|</span>
        <a href="">招聘人才</a>
        <span>|</span>
        <a href="">友情链接</a>
    </div>
    <p class="copyright">
        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>
        电话：010-****888 京ICP备*******8号
    </p>
</div>

{% endblock %}
<!-- 登录表单 -->
<form class="login_form_con">
    <div class="login_form">
        <div class="login_title">
            <h3>登 录</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input id="mobile" type="text" name="mobile" autocomplete="off">
            <div class="input_tip">手机号</div>
            <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input id="password" type="password" name="password">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="login-password-err" class="error_tip">密码不能为空</div>
        </div>
        <input type="submit" name="" value="登 录" class="input_sub">
        <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
    </div>
    <div class="mask"></div>
</form>

<!-- 注册表单 -->
<form class="register_form_con">
    <div class="register_form">
        <div class="register_title">
            <h3>注 册</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
            <div class="input_tip">手机号</div>
            <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
            <div class="input_tip">图形验证码</div>
            <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
            <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="smscode" id="smscode" class="code_pwd">
            <div class="input_tip">手机验证码</div>
            <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
            <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
        </div>
        <div class="form_group">
            <input type="password" name="password" id="register_password" class="pass_input">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="register-password-err" class="error_tip">密码不能为空</div>
        </div>
        <div class="form_group2 clearfix">
            <input type="checkbox" class="agree_input" checked>
            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
            <div class="error_tip">请勾选</div>
        </div>
        <input type="submit" name="" value="注 册" class="input_sub">
        <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
    </div>
    <div class="mask"></div>
</form>
</body>
</html>

info/templates/news/index.html
{% extends "news/base.html" %}


{% block title_block %}
    <title>首页-新经资讯</title>
{% endblock %}

{% block scirpt_block %}
    <script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}


{% block category_block %}
    <ul class="menu fl">
        {% for category in categories %}
            <li {% if loop.index == 1 %}class="active"{% endif %} data-cid="{{ category.id }}"><a
                    href="javascript:;">{{ category.name }}</a></li>
        {% endfor %}

    </ul>
{% endblock %}


{% block content_block %}
    <ul class="list_con fl">
    </ul>
{% endblock %}

info/templates/news/user.html
{% extends "news/base.html" %}


{% block title_block %}
    <title>用户中心</title>
{% endblock %}


{% block scirpt_block %}
    <script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
{% endblock %}


{% block content_block %}
    <div class="user_menu_con fl">
        <div class="user_center_pic">
            <img {% if user.avatar_url %}src="{{ user.avatar_url }}" {% else %}src="../../static/news/images/user_pic.png"{% endif %} alt="用户图片">
        </div>
        <div class="user_center_name">{{ user.nick_name }}</div>

        <ul class="option_list">
            <li class="active"><a href="{{ url_for("user.base_info") }}" target="main_frame">基本资料</a></li>
            <li><a href="{{ url_for("user.pic_info") }}" target="main_frame">头像设置</a></li>
            <li><a href="{{ url_for("user.user_follow") }}" target="main_frame">我的关注</a></li>
            <li><a href="../../static/news/html/user_pass_info.html" target="main_frame">密码修改</a></li>
            <li><a href="{{ url_for("user.collection") }}" target="main_frame">我的收藏</a></li>
            <li><a href="{{ url_for("user.news_release") }}" target="main_frame">新闻发布</a></li>
            <li><a href="{{ url_for("user.news_list") }}" target="main_frame">新闻列表</a></li>
        </ul>
    </div>

    <div class="user_con fr">
        <iframe src="{{ url_for("user.base_info") }}" frameborder="0" name="main_frame" class="main_frame"
                id="main_frame"></iframe>
    </div>
{% endblock %}


{% block rank_block %}
{% endblock %}

info/templates/news/user_collection.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/jquery.pagination.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="../../static/news/js/jquery.pagination.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/page_control.js"></script>
</head>
<body class="inframe_body">
    <div class="my_collect">
        <h3>我的收藏</h3>
        <ul class="article_list">
            {% for news in data.news_list %}
                <li><a href="/news/{{ news.id }}" target="_blank">{{ news.title }}</a><span>{{ news.create_time }}</span></li>
            {% endfor %}

        </ul>



        <div id="pagination" class="page" cur_page="{{ data.cur_page }}" total_page="{{ data.total_page }}" source="{{ url_for("user.collection") }}"></div>
    </div>
</body>
</html>

info/templates/news/user_follow.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>用户中心</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/jquery.pagination.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/jquery.pagination.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/user_follow.js"></script>
    <script type="text/javascript" src="../../static/news/js/page_control.js"></script>
    <script type="text/javascript" src="../../static/news/js/csrf.js"></script>
</head>

<body class="inframe_body">
<h3 class="common_title">我的关注</h3>

    {% for author in data.author_list %}

        <ul class="card_list_con">
            <li class="author_card card_list">
                <a href="/user/other?user_id=1" target="_blank" class="author_pic"><img {% if author.avatar_url %}src="{{ author.avatar_url }}" {% else %}src="../../static/news/images/cat.jpg"{% endif %}
                                                                                        alt="author_pic"></a>
                <a href="/user/other?user_id=1" target="_blank" class="author_name">{{ author.nick_name }}</a>
                <div class="author_resume">{{ author.signature }}</div>
                <div class="writings"><span>总篇数</span><b>{{ author.news_count }}</b></div>
                <div class="follows"><span>粉丝</span><b>{{ author.followers_count }}</b></div>
                <a href="javascript:;" class="focus fr" style="display: none" data-userid="{{ author.id }}">关注</a>
                <a href="javascript:;" class="focused fr" style="display: block" data-userid="{{ author.id }}"><span class="out">已关注</span><span class="over">取消关注</span></a>
            </li>
        </ul>

    {% endfor %}
<div id="pagination" class="page" cur_page="{{ data.cur_page }}" total_page="{{ data.total_page }}" source="{{ url_for("user.user_follow") }}"></div>
</body>

</html>